import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { Alert, Pressable, ScrollView, StyleSheet, Text } from "react-native";
import { Button, Card, Eyebrow, Loading } from "@/components/rt-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { formatDate } from "@/lib/ruang-tumbuh-data";
import { useRuangTumbuh } from "@/lib/ruang-tumbuh-store";
export default function Detail(){const c=useColors();const{id}=useLocalSearchParams<{id:string}>();const{data,ready,removeReflection}=useRuangTumbuh();if(!ready)return <Loading/>;const entry=data.reflections.find((item)=>item.id===id);if(!entry)return <ScreenContainer className="p-5"><Text style={{color:c.foreground}}>Catatan tidak ditemukan.</Text></ScreenContainer>;const remove=()=>Alert.alert("Hapus refleksi?","Catatan dan status latihan terkait akan dihapus dari perangkat ini.",[{text:"Batal",style:"cancel"},{text:"Hapus",style:"destructive",onPress:()=>{removeReflection(entry.id);router.replace("/(tabs)/reflections" as never)}}]);return <ScreenContainer className="px-5" edges={["top","bottom","left","right"]}><ScrollView contentContainerStyle={s.content}><Pressable onPress={()=>router.back()} style={s.back}><MaterialIcons name="arrow-back" size={21} color={c.foreground}/><Text style={{color:c.foreground,fontWeight:"700"}}>Kembali</Text></Pressable><Eyebrow>{entry.category.toUpperCase()}</Eyebrow><Text style={[s.title,{color:c.foreground}]}>{entry.title}</Text><Text style={{color:c.muted,fontSize:13}}>{formatDate(entry.date)}{entry.emotions?` · ${entry.emotions}`:""}</Text><Card><Eyebrow>APA YANG TERJADI</Eyebrow><Text style={[s.copy,{color:c.foreground}]}>{entry.event}</Text></Card>{entry.lesson?<Card><Eyebrow>YANG KUPELAJARI</Eyebrow><Text style={[s.copy,{color:c.foreground}]}>{entry.lesson}</Text></Card>:null}{entry.action?<Card style={{backgroundColor:"#FCE8E1",borderColor:"#F3C7BA"}}><Eyebrow>EKSPERIMEN PERILAKU</Eyebrow><Text style={[s.copy,{color:c.foreground}]}>{entry.action}</Text></Card>:null}<Button label="Hapus refleksi" onPress={remove} icon="delete-outline" quiet/></ScrollView></ScreenContainer>};const s=StyleSheet.create({content:{paddingTop:8,paddingBottom:28,gap:14},back:{flexDirection:"row",gap:6,alignItems:"center",alignSelf:"flex-start",paddingVertical:6},title:{fontSize:29,lineHeight:35,fontWeight:"800",letterSpacing:-.6},copy:{fontSize:16,lineHeight:24,fontWeight:"500"}});
