export type Category = "Kerja" | "Kuliah" | "Komunikasi" | "Hubungan" | "Kesehatan" | "Diri sendiri" | "Lainnya";
export type Outcome = "berhasil" | "sebagian" | "belum";
export type Reflection = { id: string; title: string; date: string; category: Category; emotions: string; event: string; lesson: string; action: string; createdAt: string };
export type Checkin = { sleep: string; energy: string; mood: string; water: string; movement: string; note: string };
export type Routine = { id: string; label: string; area: string; day: string };
export type Food = { id: string; name: string; calories: string; protein: string; carbs: string; fat: string };
export type Data = { reflections: Reflection[]; practices: { id: string; entryId: string; date: string; outcome: Outcome }[]; health: { checkins: Record<string, Checkin>; routines: Routine[]; routineLogs: Record<string, Record<string, boolean>>; foods: Record<string, Food[]>; calorieTarget: string } };
export const KEY = "ruang-tumbuh-native-v1";
export const CATEGORIES: Category[] = ["Kerja", "Kuliah", "Komunikasi", "Hubungan", "Kesehatan", "Diri sendiri", "Lainnya"];
export const today = (date = new Date()) => { const offset = date.getTimezoneOffset(); return new Date(date.getTime() - offset * 60000).toISOString().slice(0, 10); };
export const formatDate = (value: string, short = false) => new Intl.DateTimeFormat("id-ID", short ? { day: "numeric", month: "short" } : { day: "numeric", month: "long", year: "numeric" }).format(new Date(`${value}T12:00:00`));
export const emptyData = (): Data => ({ reflections: [], practices: [], health: { checkins: {}, routines: [], routineLogs: {}, foods: {}, calorieTarget: "" } });
export function normalize(raw: unknown): Data { const base = emptyData(); if (!raw || typeof raw !== "object") return base; const source = raw as Partial<Data>; const health = source.health ?? base.health; const foods = health.foods && typeof health.foods === "object" ? Object.fromEntries(Object.entries(health.foods).map(([date, items]) => [date, Array.isArray(items) ? items.map((item) => ({ ...item, protein: item.protein ?? "", carbs: item.carbs ?? "", fat: item.fat ?? "" })) : []])) : {}; return { reflections: Array.isArray(source.reflections) ? source.reflections : [], practices: Array.isArray(source.practices) ? source.practices : [], health: { checkins: health.checkins && typeof health.checkins === "object" ? health.checkins : {}, routines: Array.isArray(health.routines) ? health.routines : [], routineLogs: health.routineLogs && typeof health.routineLogs === "object" ? health.routineLogs : {}, foods, calorieTarget: health.calorieTarget ?? "" } }; }
export function routinesFor(data: Data, date = new Date()) { const name = ["Minggu", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu"][date.getDay()]; const common: Routine[] = [{ id: "water", label: "Isi ulang botol minum dan makan sesuai kebutuhan", area: "Makan & hidrasi", day: "Setiap hari" }, { id: "rest", label: "Siapkan ruang untuk beristirahat", area: "Istirahat", day: "Setiap hari" }]; return [...common, ...data.health.routines.filter((item) => item.day === "Setiap hari" || item.day === name)]; }
export const calories = (items: Food[]) => items.reduce((sum, item) => sum + (Number(item.calories) || 0), 0);
export const macros = (items: Food[]) => items.reduce((total, item) => ({ protein: total.protein + (Number(item.protein) || 0), carbs: total.carbs + (Number(item.carbs) || 0), fat: total.fat + (Number(item.fat) || 0) }), { protein: 0, carbs: 0, fat: 0 });
export function insights(data: Data, now = new Date()) { const start = new Date(now); start.setDate(start.getDate() - 6); start.setHours(0, 0, 0, 0); const active = (date: string) => new Date(`${date}T12:00:00`) >= start; const rs = data.reflections.filter((entry) => active(entry.date)); const ps = data.practices.filter((item) => active(item.date)); const counts = rs.reduce<Record<string, number>>((all, entry) => ({ ...all, [entry.category]: (all[entry.category] ?? 0) + 1 }), {}); const sleeps = Object.entries(data.health.checkins).filter(([date]) => active(date)).map(([, item]) => Number(item.sleep)).filter(Boolean); return { reflections: rs.length, successful: ps.filter((item) => item.outcome === "berhasil").length, attempted: ps.length, category: Object.entries(counts).sort((a, b) => b[1] - a[1])[0]?.[0] ?? "Belum cukup data", sleep: sleeps.length ? sleeps.reduce((a, b) => a + b, 0) / sleeps.length : null }; }
