import { ScrollView, StyleSheet, Text, View } from "react-native";
import { Button, Card, Eyebrow, Loading } from "@/components/rt-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { today, type Outcome } from "@/lib/ruang-tumbuh-data";
import { useRuangTumbuh } from "@/lib/ruang-tumbuh-store";
const choices:{label:string;value:Outcome}[]=[{label:"Berhasil",value:"berhasil"},{label:"Sebagian",value:"sebagian"},{label:"Belum",value:"belum"}];
export default function Practice(){const c=useColors();const{data,ready,practice}=useRuangTumbuh();if(!ready)return <Loading/>;const entries=data.reflections.filter((entry)=>entry.action);const date=today();return <ScreenContainer className="px-5"><ScrollView contentContainerStyle={s.content}><Eyebrow>LATIHAN HARIAN</Eyebrow><Text style={[s.title,{color:c.foreground}]}>Buktikan perubahan melalui langkah kecil.</Text><Text style={{color:c.muted,fontSize:14,lineHeight:20}}>Nilai ini bukan rapor tentang dirimu; ia adalah informasi agar eksperimenmu dapat diperbaiki.</Text>{entries.length?entries.map((entry)=>{const selected=data.practices.find((item)=>item.entryId===entry.id&&item.date===date)?.outcome;return <Card key={entry.id}><Text style={[s.cardTitle,{color:c.foreground}]}>{entry.title}</Text><Text style={{color:c.muted,fontSize:14,lineHeight:20}}>{entry.action}</Text><View style={s.choice}>{choices.map((item)=><Button key={item.value} label={item.label} onPress={()=>practice(entry.id,date,item.value)} icon={selected===item.value?"check":"add"} quiet={selected!==item.value}/>)}</View></Card>}):<Card><Text style={[s.cardTitle,{color:c.foreground}]}>Belum ada latihan aktif</Text><Text style={{color:c.muted,fontSize:13,lineHeight:19}}>Di akhir refleksi, pilih satu perubahan perilaku yang kecil dan realistis.</Text></Card>}</ScrollView></ScreenContainer>}
const s=StyleSheet.create({content:{paddingTop:14,paddingBottom:28,gap:14},title:{fontSize:27,lineHeight:33,fontWeight:"800",letterSpacing:-.5},cardTitle:{fontSize:17,fontWeight:"800"},choice:{gap:8,marginTop:3}});
