import { router } from "expo-router";
import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Button, Card, Eyebrow, Loading } from "@/components/rt-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { CATEGORIES, formatDate } from "@/lib/ruang-tumbuh-data";
import { useRuangTumbuh } from "@/lib/ruang-tumbuh-store";
export default function Reflections(){const c=useColors();const{data,ready}=useRuangTumbuh();const[f,setF]=useState("Semua");if(!ready)return <Loading/>;const entries=f==="Semua"?data.reflections:data.reflections.filter((item)=>item.category===f);return <ScreenContainer className="px-5"><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><Eyebrow>REFLEKSI</Eyebrow><Text style={[s.title,{color:c.foreground}]}>Temukan pola, bukan alasan untuk menghukum diri.</Text><Button label="Catat refleksi baru" onPress={()=>router.push("/capture" as never)} icon="add"/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{["Semua",...CATEGORIES].map((item)=><Pressable key={item} onPress={()=>setF(item)} style={[s.filter,{backgroundColor:f===item?c.primary:c.surface,borderColor:f===item?c.primary:c.border}]}><Text style={{color:f===item?"#fff":c.foreground,fontWeight:"700",fontSize:12}}>{item}</Text></Pressable>)}</ScrollView>{entries.length?entries.map((entry)=><Pressable key={entry.id} onPress={()=>router.push(`/reflection/${entry.id}` as never)}><Card><View style={s.meta}><Text style={{color:c.primary,fontSize:11,fontWeight:"800"}}>{entry.category}</Text><Text style={{color:c.muted,fontSize:12}}>{formatDate(entry.date,true)}</Text></View><Text style={[s.cardTitle,{color:c.foreground}]}>{entry.title}</Text><Text style={{color:c.muted,fontSize:13,lineHeight:19}} numberOfLines={3}>{entry.lesson||entry.event}</Text></Card></Pressable>):<Card><Text style={[s.cardTitle,{color:c.foreground}]}>Belum ada catatan</Text><Text style={{color:c.muted,fontSize:13,lineHeight:19}}>Catat satu kejadian saat kamu siap. Catatan ini hanya tersimpan di perangkatmu.</Text></Card>}</ScrollView></ScreenContainer>}
const s=StyleSheet.create({content:{paddingTop:14,paddingBottom:28,gap:14},title:{fontSize:27,lineHeight:33,fontWeight:"800",letterSpacing:-.5},filters:{gap:8,paddingVertical:2},filter:{borderWidth:1,paddingHorizontal:12,paddingVertical:8,borderRadius:99},meta:{flexDirection:"row",justifyContent:"space-between"},cardTitle:{fontSize:17,fontWeight:"800"}});
